package cc.agentcook.api.demo;

import cc.agentcook.api.ApiIntegrationTestBase;
import cc.agentcook.domain.permission.Permission;
import cc.agentcook.domain.permission.PermissionRepository;
import cc.agentcook.domain.plugin.Plugin;
import cc.agentcook.domain.plugin.PluginKind;
import cc.agentcook.domain.plugin.PluginRepository;
import cc.agentcook.domain.user.UserId;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Day 25 Phase 2 review — runs the five business endpoints end-to-end
 * against a real Spring Boot + Testcontainers Postgres stack and writes
 * the request/response transcript to {@code target/live-endpoint-demo.md}.
 *
 * <p>This is the reproducible substitute for "manual {@code mvn
 * spring-boot:run} + curl" demos: every {@code mvn test} run regenerates
 * the transcript, so reviewers can read the exact wire output without
 * starting anything by hand.</p>
 */
class LiveEndpointDemoTest extends ApiIntegrationTestBase {

    @Autowired private TestRestTemplate restTemplate;
    @Autowired private PluginRepository pluginRepository;
    @Autowired private PermissionRepository permissionRepository;

    @Test
    void runsAllFiveEndpointsAndWritesDemoTranscript() throws Exception {
        ObjectMapper json = new ObjectMapper();
        StringBuilder transcript = new StringBuilder();
        transcript.append("# Live Endpoint Demo — agentcook-java\n\n");
        transcript.append("Generated by `LiveEndpointDemoTest` against a fresh Spring Boot + ");
        transcript.append("Testcontainers postgres stack. Re-run with `mvn -pl agentcook-api test`.\n\n");

        // 1) POST /api/v1/users
        ResponseEntity<String> create = restTemplate.exchange(
                "/api/v1/users", org.springframework.http.HttpMethod.POST,
                jsonEntity("""
                        {"email":"alice@phase2-review.example","nickname":"Alice"}
                        """),
                String.class);
        assertEquals(201, create.getStatusCode().value());
        assertTrue(create.getHeaders().getLocation() != null
                && create.getHeaders().getLocation().getPath().startsWith("/api/v1/users/"));
        appendInteraction(transcript, "POST /api/v1/users", create);
        UUID userId = UUID.fromString(json.readTree(create.getBody()).get("id").asText());

        // 2) GET /api/v1/users/{id}
        ResponseEntity<String> getUser = restTemplate.getForEntity(
                "/api/v1/users/" + userId, String.class);
        assertEquals(200, getUser.getStatusCode().value());
        assertEquals("alice@phase2-review.example",
                json.readTree(getUser.getBody()).get("email").asText());
        appendInteraction(transcript, "GET /api/v1/users/{id}", getUser);

        // 3) POST /api/v1/sessions
        ResponseEntity<String> session = restTemplate.exchange(
                "/api/v1/sessions", org.springframework.http.HttpMethod.POST,
                jsonEntity("""
                        {"userId":"%s","title":"Phase 2 review demo"}
                        """.formatted(userId)),
                String.class);
        assertEquals(201, session.getStatusCode().value());
        appendInteraction(transcript, "POST /api/v1/sessions", session);

        // 4) Seed a published plugin + grant the user activate permission.
        Plugin plugin = Plugin.create("dingtalk-bot", "1.0.0", PluginKind.WEBHOOK, "phase2 review demo");
        plugin.publish();
        Plugin saved = pluginRepository.save(plugin);
        permissionRepository.save(
                Permission.grant(UserId.from(userId), "plugin:dingtalk-bot", "activate"));

        // 5) GET /api/v1/plugins
        ResponseEntity<String> list = restTemplate.getForEntity("/api/v1/plugins", String.class);
        assertEquals(200, list.getStatusCode().value());
        JsonNode listBody = json.readTree(list.getBody());
        assertEquals(1, listBody.size());
        assertEquals("dingtalk-bot", listBody.get(0).get("name").asText());
        appendInteraction(transcript, "GET /api/v1/plugins", list);

        // 6) POST /api/v1/plugins/{id}/activate
        ResponseEntity<String> activate = restTemplate.exchange(
                "/api/v1/plugins/" + saved.getId().value() + "/activate",
                org.springframework.http.HttpMethod.POST,
                jsonEntity("""
                        {"userId":"%s","connectorConfig":"{\\"webhook\\":\\"https://example.com\\"}"}
                        """.formatted(userId)),
                String.class);
        assertEquals(200, activate.getStatusCode().value());
        assertEquals("CONNECTED",
                json.readTree(activate.getBody()).get("status").asText());
        appendInteraction(transcript, "POST /api/v1/plugins/{id}/activate", activate);

        Path out = Path.of("target", "live-endpoint-demo.md");
        Files.createDirectories(out.getParent());
        Files.writeString(out, transcript.toString());
    }

    private static HttpEntity<String> jsonEntity(String body) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        return new HttpEntity<>(body, headers);
    }

    private static void appendInteraction(StringBuilder buf, String label, ResponseEntity<String> resp) {
        buf.append("## ").append(label).append("\n\n");
        buf.append("→ ").append(resp.getStatusCode()).append("\n\n");
        buf.append("```json\n").append(resp.getBody() == null ? "" : resp.getBody().trim()).append("\n```\n\n");
    }
}
