apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentcook.fullname" . }}-secret
  labels:
    {{- include "agentcook.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.dbPassword | default "cGFzc3dvcmQ=" | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | default "c2VjcmV0" | b64enc | quote }}
