/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents/{agent_id}/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an Agent's immutable identity card (ADR-011 layer 1). */
        get: operations["get_identity_api_v1_agents__agent_id__identity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/memory/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List memory events (cursor pagination, oldest → newest within page). */
        get: operations["list_memory_events_api_v1_agents__agent_id__memory_events_get"];
        put?: never;
        /** Append a memory event (ADR-011 layer 3 event stream). */
        post: operations["append_memory_event_api_v1_agents__agent_id__memory_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/memory/flush": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flush memory events; Identity preserved (immutable). Soul optionally preserved. */
        post: operations["flush_memory_api_v1_agents__agent_id__memory_flush_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/memory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic recall (v1 cosine; hybrid BM25 fusion Day 22). */
        post: operations["search_memory_api_v1_agents__agent_id__memory_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/soul": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current (latest) SoulConfig version. */
        get: operations["get_soul_latest_api_v1_agents__agent_id__soul_get"];
        put?: never;
        /** Append a new SoulConfig version (ADR-011 layer 2, append-only). */
        post: operations["append_soul_api_v1_agents__agent_id__soul_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/soul/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all SoulConfig versions (oldest → newest), capped. */
        get: operations["list_soul_history_api_v1_agents__agent_id__soul_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available skills
         * @description Return all registered skills (no pagination today — B's Day 28
         *     view caps at < 100 items; revisit when that no longer holds).
         */
        get: operations["list_skills_api_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single skill's manifest + body */
        get: operations["get_skill_api_v1_skills__skill_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{skill_id}/test/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a skill with test input and stream the result via SSE */
        post: operations["test_skill_stream_api_v1_skills__skill_id__test_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorEnvelope
         * @description Flat error shape — matches frontend-conventions §7.6 (B canonical).
         */
        ErrorEnvelope: {
            /**
             * Code
             * @description Machine-readable error code (UPPER_SNAKE).
             */
            code: string;
            /**
             * Detail
             * @description Optional structured context.
             */
            detail?: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @description Human-readable description.
             */
            message: string;
        };
        /** FlushRequest */
        FlushRequest: {
            /**
             * Confirm
             * @description Exact string required to prevent accidental flush.
             * @constant
             */
            confirm: "I understand this deletes all events for this agent.";
            /**
             * Preserve Identity And Soul
             * @default true
             */
            preserve_identity_and_soul: boolean;
        };
        /** FlushResponse */
        FlushResponse: {
            /** Deleted Event Count */
            deleted_event_count: number;
            /** Identity Preserved */
            identity_preserved: boolean;
            /** Soul Preserved */
            soul_preserved: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdentityResponse */
        IdentityResponse: {
            /**
             * Created At
             * @description ISO-8601 UTC timestamp
             */
            created_at: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Scopes */
            scopes?: string[];
        };
        /**
         * MemoryEventCreate
         * @description Body for ``POST /agents/{id}/memory/events``.
         *
         *     Server assigns ``id`` and (if omitted) ``timestamp``.
         */
        MemoryEventCreate: {
            /** Content */
            content: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "observation" | "decision" | "tool_use" | "user_input" | "reflection";
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Source */
            source?: string | null;
            /**
             * Timestamp
             * @description ISO-8601 UTC. If omitted, server sets it at write time.
             */
            timestamp?: string | null;
        };
        /**
         * MemoryEventListResponse
         * @description Cursor-pagination response.
         *
         *     Note: per `frontend-conventions §7.6` constraint #5 list endpoints
         *     should expose ``{items, total, page, size}``. Memory event listing
         *     intentionally uses **cursor pagination** instead (event streams are
         *     append-only — page/size becomes unstable as new events arrive).
         *     Documented exception; flagged in §7 increment to B.
         */
        MemoryEventListResponse: {
            /** Items */
            items?: components["schemas"]["MemoryEventResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** MemoryEventResponse */
        MemoryEventResponse: {
            /** Content */
            content: string;
            /**
             * Id
             * @description String id to avoid enumeration attacks.
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "observation" | "decision" | "tool_use" | "user_input" | "reflection";
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Source */
            source?: string | null;
            /** Timestamp */
            timestamp: string;
        };
        /** MemoryHitResponse */
        MemoryHitResponse: {
            /** Content */
            content: string;
            event?: components["schemas"]["MemoryEventResponse"] | null;
            /** Score */
            score: number;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Hits */
            hits?: components["schemas"]["MemoryHitResponse"][];
            /** Query */
            query: string;
        };
        /**
         * SkillDetailResponse
         * @description ``GET /api/v1/skills/{id}`` — adds the skill body (markdown + frontmatter).
         */
        SkillDetailResponse: {
            /**
             * Body
             * @description Raw skill body (markdown). Empty for placeholder skills.
             */
            body: string;
            /**
             * Category
             * @description Loose grouping (memory / nlp / chat / ...).
             */
            category: string;
            /**
             * Description
             * @description One-line summary.
             */
            description: string;
            /**
             * Id
             * @description Stable skill identifier (kebab-case).
             */
            id: string;
            /**
             * Name
             * @description Display name.
             */
            name: string;
            /**
             * Updated At
             * @description ISO-8601 UTC timestamp of last edit.
             */
            updated_at: string;
            /**
             * Version
             * @description Semver string from the skill manifest.
             */
            version: string;
        };
        /**
         * SkillListResponse
         * @description Envelope for the skill list endpoint.
         */
        SkillListResponse: {
            /**
             * Items
             * @description Skills, ordered as the registry yields them.
             */
            items: components["schemas"]["SkillSummary"][];
            /**
             * Total
             * @description Total count — equals ``len(items)`` until pagination lands.
             */
            total: number;
        };
        /**
         * SkillSummary
         * @description One row in ``GET /api/v1/skills`` — what B's SkillListView shows.
         */
        SkillSummary: {
            /**
             * Category
             * @description Loose grouping (memory / nlp / chat / ...).
             */
            category: string;
            /**
             * Description
             * @description One-line summary.
             */
            description: string;
            /**
             * Id
             * @description Stable skill identifier (kebab-case).
             */
            id: string;
            /**
             * Name
             * @description Display name.
             */
            name: string;
            /**
             * Updated At
             * @description ISO-8601 UTC timestamp of last edit.
             */
            updated_at: string;
            /**
             * Version
             * @description Semver string from the skill manifest.
             */
            version: string;
        };
        /**
         * SkillTestRequest
         * @description Body for ``POST /api/v1/skills/{id}/test/stream``.
         *
         *     The ``input`` is whatever the SkillTestDialog's textarea contains;
         *     structured ``args`` may be added later (Phase 5 once real skill
         *     schemas are loaded). Today the SSE mock ignores ``args`` and just
         *     echoes ``input`` back through the streamed chunks.
         */
        SkillTestRequest: {
            /**
             * Args
             * @description Optional structured args (Phase 5).
             */
            args?: {
                [key: string]: unknown;
            } | null;
            /**
             * Input
             * @description Free-form test input the skill will receive.
             */
            input: string;
        };
        /** SoulConfigBody */
        SoulConfigBody: {
            /** Custom Traits */
            custom_traits?: {
                [key: string]: string;
            };
            /**
             * Language Style
             * @default concise
             */
            language_style: string;
            /**
             * Tone
             * @default neutral
             */
            tone: string;
            /** Values */
            values?: string[];
        };
        /** SoulHistoryResponse */
        SoulHistoryResponse: {
            /** Items */
            items?: components["schemas"]["SoulVersionResponse"][];
        };
        /**
         * SoulResponse
         * @description Returned with the persisted version (echoes input on POST).
         */
        SoulResponse: {
            /** Custom Traits */
            custom_traits?: {
                [key: string]: string;
            };
            /**
             * Language Style
             * @default concise
             */
            language_style: string;
            /**
             * Tone
             * @default neutral
             */
            tone: string;
            /** Values */
            values?: string[];
        };
        /**
         * SoulVersionResponse
         * @description A single point in the per-agent soul history.
         */
        SoulVersionResponse: {
            config: components["schemas"]["SoulConfigBody"];
            /** Created At */
            created_at: string;
            /** Version */
            version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_identity_api_v1_agents__agent_id__identity_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityResponse"];
                };
            };
            /** @description Malformed request body (e.g. invalid JSON). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authenticated user lacks required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Agent not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method not allowed on this path. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Path / query / body validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_memory_events_api_v1_agents__agent_id__memory_events_get: {
        parameters: {
            query?: {
                /** @description ISO-8601 UTC lower bound. */
                since?: string | null;
                kind?: ("observation" | "decision" | "tool_use" | "user_input" | "reflection") | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEventListResponse"];
                };
            };
            /** @description Malformed request body (e.g. invalid JSON). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authenticated user lacks required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Agent not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method not allowed on this path. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Path / query / body validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    append_memory_event_api_v1_agents__agent_id__memory_events_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEventResponse"];
                };
            };
            /** @description Malformed request body (e.g. invalid JSON). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authenticated user lacks required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Agent not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method not allowed on this path. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Path / query / body validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    flush_memory_api_v1_agents__agent_id__memory_flush_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlushResponse"];
                };
            };
            /** @description Malformed request body (e.g. invalid JSON). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authenticated user lacks required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Agent not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method not allowed on this path. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Confirm string missing or wrong. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    search_memory_api_v1_agents__agent_id__memory_search_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Malformed request body (e.g. invalid JSON). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authenticated user lacks required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Agent not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method not allowed on this path. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Path / query / body validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_soul_latest_api_v1_agents__agent_id__soul_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoulResponse"];
                };
            };
            /** @description Malformed request body (e.g. invalid JSON). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authenticated user lacks required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Agent not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method not allowed on this path. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Path / query / body validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    append_soul_api_v1_agents__agent_id__soul_post: {
        parameters: {
            query?: never;
            header?: {
                "x-confirm-identity-change"?: boolean | null;
                authorization?: string | null;
            };
            path: {
                /** @description Agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoulConfigBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoulVersionResponse"];
                };
            };
            /** @description Malformed request body (e.g. invalid JSON). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authenticated user lacks required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Agent not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method not allowed on this path. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description X-Confirm-Identity-Change header required to mutate Soul. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Path / query / body validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_soul_history_api_v1_agents__agent_id__soul_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoulHistoryResponse"];
                };
            };
            /** @description Malformed request body (e.g. invalid JSON). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Authenticated user lacks required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Agent not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method not allowed on this path. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Path / query / body validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_skills_api_v1_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListResponse"];
                };
            };
        };
    };
    get_skill_api_v1_skills__skill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill identifier */
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetailResponse"];
                };
            };
            /** @description Skill not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_skill_stream_api_v1_skills__skill_id__test_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill identifier */
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillTestRequest"];
            };
        };
        responses: {
            /** @description SSE stream of skill execution chunks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Skill not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
