/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user. */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open a new conversation session for an existing user. */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a plugin for a user -- establishes a Connector. */
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a user by id. */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a session by id. */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List plugins, optionally filtered by status. */
        get: operations["listPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Payload to register a new user. */
        CreateUserRequest: {
            /** @example alice@example.com */
            email: string;
            /** @example Alice */
            nickname?: string;
        };
        /** @description Flat error envelope. Field names match frontend-conventions Â§7.6 (B canonical). */
        ApiError: {
            /** @example DUPLICATE_EMAIL */
            code?: string;
            /** @example User already exists with email: alice@example.com */
            message?: string;
        };
        /** @description User aggregate snapshot. */
        UserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            nickname?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DELETED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description Payload to open a conversation session for an existing user. */
        CreateSessionRequest: {
            /**
             * Format: uuid
             * @example 8aa3f6e6-3a9c-4f1f-9f1c-9f8b9c1d2e3f
             */
            userId: string;
            /** @example Trip planning */
            title?: string;
        };
        /** @description Session aggregate snapshot. */
        SessionResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            title?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "ARCHIVED" | "DELETED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description Payload to activate a plugin for a user, establishing a Connector. */
        ActivatePluginRequest: {
            /**
             * Format: uuid
             * @example 8aa3f6e6-3a9c-4f1f-9f1c-9f8b9c1d2e3f
             */
            userId: string;
            /** @example {"webhook_url":"https://example.com/webhook"} */
            connectorConfig?: string;
        };
        /** @description Connector aggregate snapshot returned by activate-plugin. */
        ConnectorResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            pluginId?: string;
            status?: string;
        };
        /** @description Plugin aggregate snapshot. */
        PluginResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            version?: string;
            /** @enum {string} */
            kind?: "MCP" | "HTTP" | "OAUTH" | "WEBHOOK";
            description?: string;
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED" | "DEPRECATED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivatePluginRequest"];
            };
        };
        responses: {
            /** @description Connector established. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConnectorResponse"];
                };
            };
            /** @description User lacks activate permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Plugin not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    listPlugins: {
        parameters: {
            query?: {
                /** @description Optional status filter (DRAFT/PUBLISHED/DEPRECATED). */
                status?: "DRAFT" | "PUBLISHED" | "DEPRECATED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PluginResponse"][];
                };
            };
        };
    };
}
